### ISSUE TITLE
No implementation found for int com.easy.ChIME.CTextGen.cleanInput()

### ISSUE THREAD

**Issue by anbo724** [amweis/ChIME#1]
11-22 12:06:38.059 3373-3373/? I/zygote: Not late-enabling -Xcheck:jni (already on)
11-22 12:06:38.066 3373-3373/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
11-22 12:06:38.296 3373-3373/com.easy.ChIME I/InstantRun: starting instant run server: is main process
11-22 12:06:38.339 3373-3402/com.easy.ChIME E/zygote: No implementation found for int com.easy.ChIME.CTextGen.cleanInput() (tried Java_com_easy_ChIME_CTextGen_cleanInput and Java_com_easy_ChIME_CTextGen_cleanInput__)
11-22 12:06:38.340 3373-3402/com.easy.ChIME E/AndroidRuntime: FATAL EXCEPTION: Thread-4
                                                              Process: com.easy.ChIME, PID: 3373
                                                              java.lang.UnsatisfiedLinkError: No implementation found for int com.easy.ChIME.CTextGen.cleanInput() (tried Java_com_easy_ChIME_CTextGen_cleanInput and Java_com_easy_ChIME_CTextGen_cleanInput__)
                                                                  at com.easy.ChIME.CTextGen.cleanInput(Native Method)
                                                                  at com.easy.ChIME.CTextGen.cleanInputCodes(CTextGen.java:296)
                                                                  at com.easy.ChIME.CTextGen.release(CTextGen.java:55)
                                                                  at com.easy.ChIME.ChIME.changeTextType(ChIME.java:102)
                                                                  at com.easy.ChIME.ChIME.run(ChIME.java:625)
                                                                  at java.lang.Thread.run(Thread.java:764)
11-22 12:06:38.342 3373-3373/com.easy.ChIME E/zygote: No implementation found for int com.easy.ChIME.CTextGen.cleanInput() (tried Java_com_easy_ChIME_CTextGen_cleanInput and Java_com_easy_ChIME_CTextGen_cleanInput__)
11-22 12:06:38.342 3373-3373/com.easy.ChIME D/AndroidRuntime: Shutting down VM
11-22 12:06:38.342 3373-3373/com.easy.ChIME I/Process: Sending signal. PID: 3373 SIG: 9

how to fix it?

**Comment by anbo724** [comment]
i copy the .so fles into lib file and fix it, however, a new problem occurs.

11-23 01:36:21.210: A/libc(3507): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x1110168013f in tid 3521 (Thread-304)
11-23 01:36:21.307: D/(3507): HostConnection::get() New Host Connection established 0x7fa2c11d6940, tid 3507
